apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-merlin-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-merlin-2.0.4
  publisher: IBM
  image: icr.io/cpopen/ibmi-merlin-operator-catalog@sha256:1481454b6a3b395d60c9a3bb3954a0b97f65bec6d05487cc59ba1bfb2f87a7a6
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
